version: 2.1

orbs:
    node: circleci/node@1.1.6

workflows:
    default:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master # Only deploys when the commit is on the Master branch

jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm run build
    deploy:
        executor:
            name: node/default
        steps:
            - run: apt-get update
            - run: apt-get install ftp-upload
            - run: ftp-upload -h '${FTP_HOST}' -u '${FTP_USERNAME}' --password '${FTP_PASSWORD}' -d 'nexteria-feedback-automation-v2' .
