version: 2.1

orbs:
    node: circleci/node@1.1.6

workflows:
    default:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master # Only deploys when the commit is on the Master branch

jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: yarn install
            - run: yarn build
            - persist_to_workspace:
                  root: .
                  paths:
                      - build/*

    deploy:
        executor:
            name: node/default
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: sudo apt-get update
            - run: sudo apt-get install ncftp
            - run: ncftpput -R -v -u "${FTP_USERNAME}" -p "${FTP_PASSWORD}" "${FTP_HOST}" / build/*
